"""Initial schema

Revision ID: b43c7bba0258
Revises: 
Create Date: 2026-03-21 22:54:52.836421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b43c7bba0258'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trilhas_aprendizado',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('modulos_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pontos_recompensa', sa.Integer(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='evolucao'
    )
    op.create_table('usuarios_pais',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pontos_gamificacao', sa.Integer(), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.Column('trilhas_concluidas', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('progresso_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='evolucao'
    )
    op.create_index(op.f('ix_evolucao_usuarios_pais_email'), 'usuarios_pais', ['email'], unique=True, schema='evolucao')
    op.create_table('alertas_seguranca',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('precisao_metros', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notificacoes_enviadas', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['evolucao.usuarios_pais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='evolucao'
    )
    op.create_index(op.f('ix_evolucao_alertas_seguranca_usuario_id'), 'alertas_seguranca', ['usuario_id'], unique=False, schema='evolucao')
    op.create_table('interacoes_ia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('pergunta_criptografada', sa.Text(), nullable=False),
    sa.Column('resposta_criptografada', sa.Text(), nullable=False),
    sa.Column('hash_anonimo', sa.String(length=64), nullable=False),
    sa.Column('categoria_tema', sa.String(length=100), nullable=True),
    sa.Column('tokens_usados', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['evolucao.usuarios_pais.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='evolucao'
    )
    op.create_index(op.f('ix_evolucao_interacoes_ia_hash_anonimo'), 'interacoes_ia', ['hash_anonimo'], unique=False, schema='evolucao')
    op.create_table('medidas_protetivas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('latitude_centro', sa.Float(), nullable=False),
    sa.Column('longitude_centro', sa.Float(), nullable=False),
    sa.Column('raio_metros', sa.Integer(), nullable=False),
    sa.Column('descricao_zona', sa.String(length=255), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['evolucao.usuarios_pais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='evolucao'
    )
    op.create_index(op.f('ix_evolucao_medidas_protetivas_usuario_id'), 'medidas_protetivas', ['usuario_id'], unique=False, schema='evolucao')
    op.create_table('transacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('gateway_id', sa.String(length=255), nullable=True),
    sa.Column('valor_centavos', sa.Integer(), nullable=False),
    sa.Column('moeda', sa.String(length=3), nullable=True),
    sa.Column('metodo', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('plano', sa.String(length=100), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['evolucao.usuarios_pais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='evolucao'
    )
    op.create_index(op.f('ix_evolucao_transacoes_gateway_id'), 'transacoes', ['gateway_id'], unique=True, schema='evolucao')
    op.create_index(op.f('ix_evolucao_transacoes_usuario_id'), 'transacoes', ['usuario_id'], unique=False, schema='evolucao')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evolucao_transacoes_usuario_id'), table_name='transacoes', schema='evolucao')
    op.drop_index(op.f('ix_evolucao_transacoes_gateway_id'), table_name='transacoes', schema='evolucao')
    op.drop_table('transacoes', schema='evolucao')
    op.drop_index(op.f('ix_evolucao_medidas_protetivas_usuario_id'), table_name='medidas_protetivas', schema='evolucao')
    op.drop_table('medidas_protetivas', schema='evolucao')
    op.drop_index(op.f('ix_evolucao_interacoes_ia_hash_anonimo'), table_name='interacoes_ia', schema='evolucao')
    op.drop_table('interacoes_ia', schema='evolucao')
    op.drop_index(op.f('ix_evolucao_alertas_seguranca_usuario_id'), table_name='alertas_seguranca', schema='evolucao')
    op.drop_table('alertas_seguranca', schema='evolucao')
    op.drop_index(op.f('ix_evolucao_usuarios_pais_email'), table_name='usuarios_pais', schema='evolucao')
    op.drop_table('usuarios_pais', schema='evolucao')
    op.drop_table('trilhas_aprendizado', schema='evolucao')
    # ### end Alembic commands ###
